// Pixel animals. Each sprite is 16x16: one string per row, one character per
// pixel. "." is transparent; every other character looks up a colour in `pal`.
// To add an animal, copy an entry, redraw the rows, and give it a rarity.
// For a breed or colour variant, add a `variant(...)` line at the bottom of ANIMALS.

const EYE = '#2B1D14'

const DRAWN = [
  {
    id: 'chick',
    name: 'Chick',
    rarity: 'common',
    pal: { k: '#6B4A12', y: '#FFD84A', Y: '#F2B32C', o: '#F58A1F', e: EYE, p: '#FF9F9F' },
    px: [
      '................',
      '.......kk.......',
      '......kyyk......',
      '....kkkyykkk....',
      '...kyyyyyyyyk...',
      '..kyyyyyyyyyyk..',
      '..kyyeyyyyeyyk..',
      '..kyyeyyyyeyyk..',
      '..kypyyooyypyk..',
      '.kkyyyyooyyyykk.',
      '.kYyyyyyyyyyyYk.',
      '.kYyyyyyyyyyyYk.',
      '..kyyyyyyyyyyk..',
      '...kyyyyyyyyk...',
      '....kkokkokk....',
      '.....oo..oo.....',
    ],
  },
  {
    id: 'bunny',
    name: 'Bunny',
    rarity: 'common',
    pal: { k: '#7A6A5E', w: '#FBF6EE', p: '#F7A8B8', n: '#E86A8A', e: EYE },
    px: [
      '...kk......kk...',
      '..kwwk....kwwk..',
      '..kwpk....kwpk..',
      '..kwpk....kwpk..',
      '..kwpk....kwpk..',
      '..kwwkkkkkkwwk..',
      '..kwwwwwwwwwwk..',
      '.kwwwwwwwwwwwwk.',
      '.kwwewwwwwwewwk.',
      '.kwwewwwwwwewwk.',
      '.kwpwwwnnwwwpwk.',
      '.kwwwwwwwwwwwwk.',
      '..kwwwwwwwwwwk..',
      '..kwwwwwwwwwwk..',
      '...kwwkkkkwwk...',
      '....kk....kk....',
    ],
  },
  {
    id: 'cat',
    name: 'Cat',
    rarity: 'common',
    pal: { k: '#6B3A12', o: '#F2A04A', d: '#C97428', w: '#FFF3E0', p: '#F7A8B8', n: '#E86A8A', e: EYE },
    px: [
      '................',
      '..kk........kk..',
      '.kook......kook.',
      '.kopokkkkkkopok.',
      '.kooooddddooook.',
      '.kooooooooooook.',
      '.kooeooooooeook.',
      '.kooeooooooeook.',
      '.kpoowwnnwwoopk.',
      '..kowwwwwwwwok..',
      '...kkwwwwwwkk...',
      '...koowwwwook.kk',
      '...koooooooookok',
      '...kookookookkok',
      '...kkkkkkkkkkkk.',
      '................',
    ],
  },
  {
    id: 'frog',
    name: 'Frog',
    rarity: 'common',
    pal: { k: '#24551B', g: '#6CC24A', l: '#C9EE9A', w: '#FFFFFF', p: '#F59A9A', e: EYE },
    px: [
      '................',
      '................',
      '..kkk......kkk..',
      '.kgggk....kgggk.',
      '.kgwekkkkkkwegk.',
      '.kgweggggggwegk.',
      '.kggggggggggggk.',
      '.kgpggggggggpgk.',
      '.kggkggggggkggk.',
      '.kgggkkkkkkgggk.',
      '..kggggggggggk..',
      '..kgllllllllgk..',
      '.kkgllllllllgkk.',
      '.kggkggggggkggk.',
      '..kk.kkkkkk.kk..',
      '................',
    ],
  },
  {
    id: 'pig',
    name: 'Pig',
    rarity: 'common',
    pal: { k: '#8A3D52', p: '#F9B4C0', P: '#EE8AA0', e: EYE },
    px: [
      '................',
      '................',
      '..kkk......kkk..',
      '.kpPpkkkkkkpPpk.',
      '.kppppppppppppk.',
      '.kppppppppppppk.',
      '.kppeppppppeppk.',
      '.kppeppppppeppk.',
      '.kpppPPPPPPpppk.',
      '.kpppPkPPkPpppk.',
      '.kpppPPPPPPpppk.',
      '..kppppppppppk..',
      '..kppppppppppk..',
      '..kppkppppkppk..',
      '...kk.kkkk.kk...',
      '................',
    ],
  },
  {
    id: 'mouse',
    name: 'Mouse',
    rarity: 'common',
    pal: { k: '#4A4C59', g: '#B9BCC6', p: '#F7A8B8', n: '#E86A8A', w: '#F4F4F7', e: EYE },
    px: [
      '................',
      '.kkk........kkk.',
      'kgggk......kgggk',
      'kgpgk......kgpgk',
      'kgpggkkkkkkggpgk',
      '.kggggggggggggk.',
      '.kggggggggggggk.',
      '.kggeggggggeggk.',
      '.kggeggggggeggk.',
      '.kgpgggnngggpgk.',
      '..kggwwwwwwggk..',
      '..kgwwwwwwwwgk..',
      '..kgwwwwwwwwgk..',
      '...kgwwwwwwgk...',
      '...kkkk..kkkk...',
      '................',
    ],
  },
  {
    id: 'dog',
    name: 'Dog',
    rarity: 'common',
    pal: { k: '#5A3A1E', t: '#E0A867', b: '#8A5A2E', w: '#FFF6EA', n: '#2B1D14', p: '#F27A8A', e: EYE },
    px: [
      '................',
      '....kkkkkkkk....',
      '...kttttttttk...',
      '.kkttttttttttkk.',
      'kbbkttttttttkbbk',
      'kbbttettttettbbk',
      'kbbttettttettbbk',
      'kbbttwwwwwwttbbk',
      '.kbtwwwnnwwwtbk.',
      '.kkbtwwppwwtbkk.',
      '..kttttttttttk..',
      '..kttwwwwwwttk..',
      '..kttwwwwwwttk..',
      '..kttttttttttk..',
      '..kttkkkkkkttk..',
      '...kk......kk...',
    ],
  },
  {
    id: 'cow',
    name: 'Cow',
    rarity: 'common',
    pal: { k: '#3A2E2A', w: '#FBF6EE', p: '#F7B8C0', n: '#C76A7A', h: '#E8D9B0', e: EYE },
    px: [
      '.kk..........kk.',
      '.khk........khk.',
      '..khkkkkkkkkhk..',
      '.kwwwwkkwwwwwwk.',
      '.kwwwwwkwwwwwwk.',
      '.kwwewwwwwwewwk.',
      '.kwwewwwwwwewwk.',
      '.kwwwwwwwwwwwwk.',
      '.kwppppppppppwk.',
      '.kpppnppppnpppk.',
      '.kppppppppppppk.',
      '..kppppppppppk..',
      '..kwwkkwwwwwwk..',
      '..kwkkkwwwwwwk..',
      '..kwwkkkkkkwwk..',
      '...kk......kk...',
    ],
  },
  {
    id: 'sheep',
    name: 'Sheep',
    rarity: 'common',
    pal: { k: '#5E5048', w: '#FBF6EE', g: '#E3DACB', f: '#4A3B33', e: '#FFF6EA' },
    px: [
      '....kk.kk.kk....',
      '...kwwkwwkwwk...',
      '..kwwwwwwwwwwk..',
      '.kwwwffffffwwwk.',
      'kffkwffffffwkffk',
      'kffkfeffffefkffk',
      '.kkkfeffffefkkk.',
      '..kwwffffffwwk..',
      '.kwwwwffffwwwwk.',
      'kwwgwwwwwwwwgwwk',
      'kwwwwwwwwwwwwwwk',
      'kgwwwwgwwgwwwwgk',
      '.kwwwwwwwwwwwwk.',
      '..kgwwgwwgwwgk..',
      '..kkffkkkkffkk..',
      '....kk....kk....',
    ],
  },
  {
    id: 'duck',
    name: 'Duck',
    rarity: 'common',
    pal: { k: '#6B5A45', w: '#FBF8F2', g: '#DCD6CC', o: '#F58A1F', O: '#C9661A', p: '#FFB3B3', e: EYE },
    px: [
      '................',
      '.....kkkkkk.....',
      '....kwwwwwwk....',
      '...kwwwwwwwwk...',
      '..kwwwwwwwwwwk..',
      '..kwwewwwwewwk..',
      '..kwwewwwwewwk..',
      '..kwpkkkkkkpwk..',
      '..kwkooooookwk..',
      '..kwkOOOOOOkwk..',
      '.kwwwkkkkkkwwwk.',
      'kwgwwwwwwwwwwgwk',
      'kwggwwwwwwwwggwk',
      '.kwwwwwwwwwwwwk.',
      '..kkkokkkkokkk..',
      '....oo....oo....',
    ],
  },
  {
    id: 'hamster',
    name: 'Hamster',
    rarity: 'common',
    pal: { k: '#7A4A22', o: '#F2B266', w: '#FFF3E0', p: '#F7A8B8', n: '#E86A8A', e: EYE },
    px: [
      '................',
      '..kk........kk..',
      '.kpok......kopk.',
      '.koookkkkkkoook.',
      '.kooooooooooook.',
      '.kooeoowwooeook.',
      '.kooeowwwwoeook.',
      'kwwwowwnnwwowwwk',
      'kwppwwwwwwwwppwk',
      'kwwwwwwwwwwwwwwk',
      '.kwwwwwwwwwwwwk.',
      '.kowwwwwwwwwwok.',
      '..kowwwwwwwwok..',
      '...koowwwwook...',
      '....kkkkkkkk....',
      '................',
    ],
  },
  {
    id: 'turtle',
    name: 'Turtle',
    rarity: 'common',
    pal: { k: '#2F4A1E', g: '#9ED36A', s: '#6B8E3A', S: '#4E6B28', y: '#D9C27A', e: EYE },
    px: [
      '................',
      '......kkkk......',
      '.....kggggk.....',
      '....kggggggk....',
      '....kgeggegk....',
      '....kgeggegk....',
      '....kggggggk....',
      '..kkkkggggkkkk..',
      '.kgkssSssSsskgk.',
      '.kgksSssssSskgk.',
      '..ksssSSSSsssk..',
      '..kSssssssssSk..',
      '..kssSssssSssk..',
      '.kgkyyyyyyyykgk.',
      '.kkk.kkkkkk.kkk.',
      '................',
    ],
  },
  {
    id: 'fox',
    name: 'Fox',
    rarity: 'rare',
    pal: { k: '#6B2E0E', o: '#EE7A2E', d: '#3A2A22', w: '#FFF6EA', n: '#2B1D14', e: EYE },
    px: [
      '.kk..........kk.',
      '.kdk........kdk.',
      '.kook......kook.',
      '.koookkkkkkoook.',
      '.kooooooooooook.',
      '.kooeooooooeook.',
      '.kooeooooooeook.',
      '.kwwoooooooowwk.',
      '.kwwwwonnowwwwk.',
      '..kwwwwwwwwwwk..',
      '...kkwwwwwwkk...',
      '...koowwwwook.k.',
      '...koowwwwookkok',
      '...koooooooookwk',
      '...kkkkkkkkkkkk.',
      '................',
    ],
  },
  {
    id: 'panda',
    name: 'Panda',
    rarity: 'rare',
    pal: { k: '#2A2A33', w: '#FAFAFA', b: '#2A2A33', e: '#FFFFFF', n: '#2A2A33' },
    px: [
      '................',
      '.kkk........kkk.',
      'kbbbk......kbbbk',
      'kbbbkkkkkkkkbbbk',
      '.kkwwwwwwwwwwkk.',
      '.kwwwwwwwwwwwwk.',
      '.kwbbbwwwwbbbwk.',
      '.kwbebwwwwbebwk.',
      '.kwwbbwnnwbbwwk.',
      '.kwwwwwwwwwwwwk.',
      '..kwwwwwwwwwwk..',
      '..kbbwwwwwwbbk..',
      '..kbbwwwwwwbbk..',
      '..kbbbwwwwbbbk..',
      '...kkkkkkkkkk...',
      '................',
    ],
  },
  {
    id: 'penguin',
    name: 'Penguin',
    rarity: 'rare',
    pal: { k: '#172038', n: '#2D3E63', w: '#FAFBFF', o: '#F59A23', e: EYE },
    px: [
      '................',
      '.....kkkkkk.....',
      '....knnnnnnk....',
      '...knnnnnnnnk...',
      '..knnwwnnwwnnk..',
      '..knwwwwwwwwnk..',
      '..knwewwwwewnk..',
      '..knwwwoowwwnk..',
      '.kknwwwoowwwnkk.',
      '.knnwwwwwwwwnnk.',
      '.knnwwwwwwwwnnk.',
      '.knnwwwwwwwwnnk.',
      '..knwwwwwwwwnk..',
      '..knnwwwwwwnnk..',
      '...kookkkkook...',
      '....kk....kk....',
    ],
  },
  {
    id: 'owl',
    name: 'Owl',
    rarity: 'rare',
    pal: { k: '#4A2F17', b: '#9A6B3F', w: '#FFF8E7', o: '#F2A81D', c: '#EBD2A4', e: EYE },
    px: [
      '................',
      '..k..........k..',
      '.kbk........kbk.',
      '.kbbkkkkkkkkbbk.',
      '.kbbbbbbbbbbbbk.',
      '.kbwwwbbbbwwwbk.',
      '.kbwewbbbbwewbk.',
      '.kbwwwboobwwwbk.',
      '.kbbbbboobbbbbk.',
      '.kbbccccccccbbk.',
      '.kbbcbccccbcbbk.',
      '.kbbccccccccbbk.',
      '..kbbcbccbcbbk..',
      '...kbbbbbbbbk...',
      '....kookkook....',
      '................',
    ],
  },
  {
    id: 'koala',
    name: 'Koala',
    rarity: 'rare',
    pal: { k: '#4A4A55', g: '#A9ABB8', l: '#D9DAE3', n: '#2B2B33', w: '#F4F4F8', e: EYE },
    px: [
      '................',
      '.kkk........kkk.',
      'kllgk......kgllk',
      'kllgkkkkkkkkgllk',
      'klgggggggggggglk',
      '.kggeggggggeggk.',
      '.kggeggnnggeggk.',
      '.kggggnnnnggggk.',
      '.kggggnnnnggggk.',
      '..kggggnnggggk..',
      '...kkggggggkk...',
      '..kgwwwwwwwwgk..',
      '..kgwwwwwwwwgk..',
      '..kggwwwwwwggk..',
      '..kggkkkkkkggk..',
      '...kk......kk...',
    ],
  },
  {
    id: 'raccoon',
    name: 'Raccoon',
    rarity: 'rare',
    pal: { k: '#3A3A40', g: '#9C9AA3', d: '#3A3A40', w: '#F2F0EC', e: '#FFF6EA' },
    px: [
      '................',
      '.kk..........kk.',
      '.kwk........kwk.',
      '.kgwkkkkkkkkwgk.',
      '.kggggwwwwggggk.',
      'kwddddwwwwddddwk',
      'kddeddwwwwddeddk',
      'kwddddwwwwddddwk',
      '.kwwwwwkkwwwwwk.',
      '..kwwwwwwwwwwk..',
      '...kkggggggkk...',
      '..kggwwwwwwggk..',
      '..kggwwwwwwggkdk',
      '..kggggggggggkgk',
      '..kggkkkkkkggkdk',
      '...kk......kkkk.',
    ],
  },
  {
    id: 'hedgehog',
    name: 'Hedgehog',
    rarity: 'rare',
    pal: { k: '#4A3020', s: '#8A5A34', S: '#6B4226', f: '#F6DDB8', n: '#2B1D14', p: '#F7A8B8', e: EYE },
    px: [
      '..k.k.k..k.k.k..',
      '.kSkSkSkkSkSkSk.',
      'kSsSsSsSsSsSsSsk',
      'ksSsSsSsSsSsSsSk',
      'kSsSsffffffsSsSk',
      'ksSsffffffffsSsk',
      'kSsffeffffeffsSk',
      'ksSffeffffeffSsk',
      'kSsfpffnnffpfsSk',
      '.kSsffffffffsSk.',
      '.ksSsffffffsSsk.',
      '..kSsSffffSsSk..',
      '..ksSsSsSsSsSk..',
      '...kkkkkkkkkk...',
      '...kfk....kfk...',
      '...kk......kk...',
    ],
  },
  {
    id: 'tiger',
    name: 'Tiger',
    rarity: 'rare',
    pal: { k: '#3A2214', o: '#F28C28', d: '#3A2214', w: '#FFF6EA', n: '#E86A8A', e: EYE },
    px: [
      '................',
      '.kk..........kk.',
      '.kwk........kwk.',
      '.kookkkkkkkkook.',
      '.kooododdodoook.',
      '.kdoeooooooeodk.',
      '.kooeooooooeook.',
      '.kdowwwwwwwwodk.',
      '.kowwwwnnwwwwok.',
      '..kwwwwwwwwwwk..',
      '...kkooooookk...',
      '..kodowwwwodok..',
      '..koodwwwwdook..',
      '..kodoooooodok..',
      '..kookkkkkkook..',
      '...kk......kk...',
    ],
  },
  {
    id: 'axolotl',
    name: 'Axolotl',
    rarity: 'legendary',
    pal: { k: '#9A3A63', a: '#FFB7CE', l: '#FFE0EA', f: '#E8498A', p: '#FF8FB0', e: EYE },
    px: [
      '................',
      '.k............k.',
      'kfk..kkkkkk..kfk',
      '.kfkkaaaaaakkfk.',
      'kfkaaaaaaaaaakfk',
      '.kkaaaaaaaaaakk.',
      'kfkaeaaaaaaeakfk',
      '.kkaeaaaaaaeakk.',
      '..kapaakkaapak..',
      '..kaaaaaaaaaak..',
      '...kkaaaaaakk...',
      '...kaallllaak...',
      '..kkaallllaakk..',
      '...kaaallaaakkk.',
      '...kkkkkkkkkaak.',
      '............kk..',
    ],
  },
  {
    id: 'capybara',
    name: 'Capybara',
    rarity: 'legendary',
    pal: { k: '#5A3A1E', b: '#B9814D', d: '#8F5E33', n: '#3A2414', o: '#F58A1F', g: '#4E9A3A', e: EYE },
    px: [
      '.......gk.......',
      '......kook......',
      '.....kooook.....',
      '..kk.kooook.kk..',
      '.kbbkkkkkkkkbbk.',
      '.kbbbbbbbbbbbbk.',
      '.kbbbbbbbbbbbbk.',
      '.kbebbbbbbbbebk.',
      '.kbbbbddddbbbbk.',
      '.kbbbdnddndbbbk.',
      '.kbbbddddddbbbk.',
      '.kbbbbbbbbbbbbk.',
      '.kbbbbbbbbbbbbk.',
      '..kbbkbbbbkbbk..',
      '..kkkkkkkkkkkk..',
      '................',
    ],
  },
  {
    id: 'unicorn',
    name: 'Unicorn',
    rarity: 'legendary',
    pal: { k: '#6A5A7A', w: '#FDFBFF', g: '#E6E0F0', y: '#FFD84A', Y: '#E8A82C', m: '#F28BC8', M: '#9A7BEA', p: '#F7B8D0', e: EYE },
    px: [
      '.......kk.......',
      '......kyYk......',
      '......kYyk......',
      '..kk..kyYk..kk..',
      '..kwkkwwwwkkwk..',
      '.kmmwwwwwwwwwwk.',
      '.kmMwwewwwwewwk.',
      '.kmMwwewwwwewwk.',
      '.kmmwpwwwwwwpwk.',
      '.kMmwwwwggwwwwk.',
      '.kmMkwwwwwwwwk..',
      '..kmmwwwwwwwwk..',
      '..kMwwwwwwwwwk..',
      '..kwwwwwwwwwwk..',
      '..kggkkkkkkggk..',
      '...kk......kk...',
    ],
  },
  {
    id: 'dragon',
    name: 'Dragon',
    rarity: 'legendary',
    pal: { k: '#2E3A4A', g: '#5FC9A8', d: '#3A9A7E', y: '#FFE7A0', h: '#FFF1C9', w: '#F28B6B', e: EYE },
    px: [
      '..k..........k..',
      '..hk........kh..',
      '..khk.kkkk.khk..',
      '...kkggggggkk...',
      '..kggggggggggk..',
      '..kggeggggeggk..',
      '..kggeggggeggk..',
      '..kgggddddgggk..',
      '..kgddkddkddgk..',
      'kk.kggggggggk.kk',
      'kwkkgyyyyyygkkwk',
      'kwwkgyyyyyygkwwk',
      '.kwkgyyyyyygkwk.',
      '..kkggggggggkk..',
      '...kggkkkkggkkgk',
      '...kkk....kkkkk.',
    ],
  },
  {
    id: 'silkie',
    name: 'Silkie Chicken',
    rarity: 'common',
    pal: { k: '#7A6E66', w: '#FFFFFF', g: '#E6E0DA', f: '#4A4060', c: '#6A2A4A', b: '#5EC8D8', o: '#8A8AA0', e: '#FFFFFF' },
    px: [
      '.....k.kk.k.....',
      '....kwkcckwk....',
      '...kwwwwwwwwk...',
      '..kwwwwwwwwwwk..',
      '.kwwwgwwwwgwwwk.',
      '.kwwkffffffkwwk.',
      'kwwkfeffffefkwwk',
      'kwwkbffooffbkwwk',
      'kwwwkkffffkkwwwk',
      'kgwwwwkkkkwwwwgk',
      'kwgwwwwwwwwwwgwk',
      'kwwgwwgwwgwwgwwk',
      '.kwwwwwwwwwwwwk.',
      '..kwgwwwwwwgwk..',
      '...kkkkkkkkkk...',
      '....ff....ff....',
    ],
  },
  {
    id: 'goat',
    name: 'Goat',
    rarity: 'common',
    pal: { k: '#5A4E44', w: '#F6F1E8', g: '#DCD3C4', h: '#A8957A', p: '#F2B8B0', n: '#3A2E28', e: EYE },
    px: [
      '..kk........kk..',
      '..khk......khk..',
      '...khk....khk...',
      '....kkkkkkkk....',
      'kkkkwwwwwwwwkkkk',
      'kpgkwwwwwwwwkgpk',
      '.kkkwewwwwewkkk.',
      '...kwewwwwewk...',
      '...kwwwwwwwwk...',
      '...kwggggggwk...',
      '...kwgnggngwk...',
      '....kggggggk....',
      '.....kwwwwk.....',
      '......kwwk......',
      '.......kk.......',
      '................',
    ],
  },
  {
    id: 'seal',
    name: 'Seal',
    rarity: 'common',
    pal: { k: '#3E4A58', g: '#A9B8C8', l: '#D6E0EA', n: '#2B2B33', e: EYE },
    px: [
      '................',
      '................',
      '.....kkkkkk.....',
      '....kggggggk....',
      '...kggggggggk...',
      '...kgeggggegk...',
      '...kgeggggegk...',
      '...kgglnnlggk...',
      '..kggllllllggk..',
      '.kggggggggggggk.',
      'kgkgllllllllgkgk',
      'kkkgllllllllgkkk',
      '..kgllllllllgk..',
      '..kggggggggggk..',
      '..kkkkkkkkkkkk..',
      '................',
    ],
  },
  {
    id: 'crocodile',
    name: 'Crocodile',
    rarity: 'rare',
    pal: { k: '#1E3A1E', g: '#5E9E3E', d: '#3E7A2E', y: '#D8E08A', w: '#FFFFFF', n: '#1E3A1E', e: '#F7D24A' },
    px: [
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '..k.k.k.kkkkk...',
      '.kdkdkdkgegggk..',
      'kdgggggggggggkkk',
      'kgggggggggggggnk',
      '.kggggggggwkwkwk',
      '..kyyyyyyykkkkkk',
      '..kgkkkkkkgk....',
      '..kk.....kk.....',
    ],
  },
  {
    id: 'sloth',
    name: 'Sloth',
    rarity: 'rare',
    pal: { k: '#4A3626', b: '#9A7A5A', f: '#EADBC4', d: '#5A4232', n: '#2B1D14', e: '#FFF6EA' },
    px: [
      '................',
      '....kkkkkkkk....',
      '...kbbbbbbbbk...',
      '..kbbbbbbbbbbk..',
      '.kbbffffffffbbk.',
      '.kbfddffffddfbk.',
      '.kbfdeffffedfbk.',
      '.kbffddffddffbk.',
      '.kbffffnnffffbk.',
      '.kbffkffffkffbk.',
      '..kbfffkkfffbk..',
      '..kbbbbbbbbbbk..',
      '.kbbbbbbbbbbbbk.',
      'kffkbbbbbbbbkffk',
      '.kkkbbbbbbbbkkk.',
      '...kkkkkkkkkk...',
    ],
  },
  {
    id: 'red-panda',
    name: 'Red Panda',
    rarity: 'rare',
    pal: { k: '#4A1E0E', r: '#C8502A', R: '#8E3418', w: '#FFF6EA', d: '#2B1610', n: '#2B1610', e: EYE },
    px: [
      '................',
      '.kk..........kk.',
      '.kwk........kwk.',
      '.kwrkkkkkkkkrwk.',
      '.krrrrrrrrrrrrk.',
      '.krwwrrrrrrwwrk.',
      '.krrerrrrrrerrk.',
      '.kRrerrrrrrerRk.',
      '.kwwwwwnnwwwwwk.',
      '..kwwwwwwwwwwk..',
      '...kkrrrrrrkk...',
      '..kdrrrrrrrrdk..',
      '..kddrrrrrrddkRk',
      '..kddddddddddkrk',
      '..kddkkkkkkddkRk',
      '...kk......kkkk.',
    ],
  },
  {
    id: 'lion',
    name: 'Lion',
    rarity: 'rare',
    pal: { k: '#5A3010', m: '#B8622A', M: '#8E4418', y: '#F2C36B', w: '#FFF0D0', n: '#4A2414', e: EYE },
    px: [
      '....kkkkkkkk....',
      '..kkmMmMmMmMkk..',
      '.kmMmmmmmmmmMmk.',
      'kMmmyyyyyyyymmMk',
      'kmmyyyyyyyyyymmk',
      'kMmyyeyyyyeyymMk',
      'kmmyyeyyyyeyymmk',
      'kMmyywwwwwwyymMk',
      'kmmywwwnnwwwymmk',
      'kMmmywwwwwwymmMk',
      '.kmMmyyyyyymMmk.',
      '..kmMmmmmmmMmk..',
      '...kkyyyyyykk...',
      '..kyyyyyyyyyyk..',
      '..kyykkkkkkyyk..',
      '...kk......kk...',
    ],
  },
  {
    id: 'elephant',
    name: 'Elephant',
    rarity: 'rare',
    pal: { k: '#4A5060', g: '#A0A8B8', G: '#7E8798', p: '#F2B8C8', w: '#FFFFFF', e: EYE },
    px: [
      '................',
      '....kkkkkkkk....',
      '.kkkggggggggkkk.',
      'kGGkggggggggkGGk',
      'kGpGggggggggGpGk',
      'kGppgeggggegppGk',
      'kGppgeggggegppGk',
      'kGpGggggggggGpGk',
      '.kGGkwggggwkGGk.',
      '..kkkkwggwkkkk..',
      '..kgggkggkgggk..',
      '..kgggkggkgggk..',
      '..kggggkkggggk..',
      '..kggggggggggk..',
      '..kggkkkkkkggk..',
      '...kk......kk...',
    ],
  },
  {
    id: 'narwhal',
    name: 'Narwhal',
    rarity: 'legendary',
    pal: { k: '#2E3E5A', b: '#6A8EC0', l: '#CFE0F2', s: '#4E6E9E', t: '#FFF6E0', p: '#F7B8D0', e: EYE },
    px: [
      '.......kk.......',
      '.......ktk......',
      '......ktk.......',
      '....kkktkkkk....',
      '...kbbbbbbbbk...',
      '..kbbsbbbbsbbk..',
      '.kbbbbbbbbbbbbk.',
      '.kbbebbbbbbebbk.',
      '.kbbebbbbbbebbk.',
      '.kbpbllllllbpbk.',
      '.kbbllllllllbbk.',
      'kbkbllllllllbkbk',
      'kkkbllllllllbkkk',
      '..kbbllllllbbk..',
      '...kkbbbbbbkk...',
      '.....kkkkkk.....',
    ],
  },
]

// Breeds and colour variants reuse another animal's pixels with a new palette.
const variant = (of, id, name, rarity, pal) => ({ id, name, rarity, pal, px: DRAWN.find((a) => a.id === of).px })

export const ANIMALS = [
  ...DRAWN,
  variant('cat', 'siamese', 'Siamese Cat', 'common', { k: '#5A4032', o: '#F3E3C8', d: '#5A4032', w: '#FFF8EC', p: '#E8A8A8', n: '#C27A7A', e: '#3A7BD5' }),
  variant('cat', 'tuxedo', 'Tuxedo Cat', 'common', { k: '#141216', o: '#38343C', d: '#25222A', w: '#FBF8F2', p: '#F7A8B8', n: '#E86A8A', e: '#E8C23A' }),
  variant('dog', 'golden', 'Golden Retriever', 'common', { k: '#7A5320', t: '#F2C36B', b: '#D8963A', w: '#FFF3D6', n: '#2B1D14', p: '#F27A8A', e: EYE }),
  variant('dog', 'black-lab', 'Black Lab', 'common', { k: '#121011', t: '#3E3638', b: '#2A2426', w: '#5A5054', n: '#121011', p: '#F27A8A', e: '#C98A3A' }),
  variant('bunny', 'brown-bunny', 'Brown Bunny', 'common', { k: '#5A3A22', w: '#C49A72', p: '#F2B8A8', n: '#E86A8A', e: EYE }),
  variant('fox', 'shiba', 'Shiba Inu', 'rare', { k: '#6B3A12', o: '#E8A050', d: '#FFF0DC', w: '#FFF6EA', n: '#2B1D14', e: EYE }),
  variant('fox', 'arctic-fox', 'Arctic Fox', 'rare', { k: '#5A6478', o: '#F4F6FA', d: '#C8D0DC', w: '#FFFFFF', n: '#2B2B33', e: EYE }),
  variant('tiger', 'white-tiger', 'White Tiger', 'legendary', { k: '#2E2A2E', o: '#F4F1EC', d: '#2E2A2E', w: '#FFFFFF', n: '#E8A0A8', e: '#3A7BD5' }),
  variant('tiger', 'snow-leopard', 'Snow Leopard', 'legendary', { k: '#4A4650', o: '#E6E4DF', d: '#7A7680', w: '#FFFFFF', n: '#E8A0A8', e: '#6FC2B4' }),
]

export const ANIMAL_BY_ID = Object.fromEntries(ANIMALS.map((a) => [a.id, a]))

export const RARITY = {
  common: { label: 'Common', weight: 72 },
  rare: { label: 'Rare', weight: 23 },
  legendary: { label: 'Legendary', weight: 5 },
}

// The egg. "s" pixels take the current mode colour, so the egg matches the theme.
export const EGG = {
  pal: { k: '#6B5A45', w: '#FFF8EC', d: '#E9D9BE', s: 'var(--accent)' },
  px: [
    '................',
    '......kkkk......',
    '.....kwwwwk.....',
    '....kwwwwwwk....',
    '....kwwsswwk....',
    '...kwwwsswwwk...',
    '...kwwwwwwwwk...',
    '..kwwwwwwwwwwk..',
    '..kwsswwwwwwwk..',
    '..kwsswwwwsswk..',
    '..kwwwwwwwsswk..',
    '..kwwwwwwwwwwk..',
    '...kwwwwwwwwk...',
    '...kddwwwwddk...',
    '....kkddddkk....',
    '......kkkk......',
  ],
}

// Cracks appear as the focus session progresses: [x, y] pixels painted dark.
export const CRACKS = [
  [],
  [[6, 8], [7, 7], [8, 6], [9, 7]],
  [[4, 6], [5, 7], [6, 8], [7, 7], [8, 6], [9, 7], [10, 8], [11, 7]],
  [[3, 7], [4, 6], [5, 7], [6, 8], [7, 7], [8, 6], [9, 7], [10, 8], [11, 7], [12, 6], [6, 9], [7, 10], [8, 5]],
]

// Pick the animal for a finished focus session.
//   minutes    - length of the session; longer sessions improve the odds of rarer animals
//   guaranteed - true on the last session before a long break: at least a rare
export function rollAnimal(minutes, guaranteed = false, rand = Math.random) {
  const luck = Math.min(2.4, Math.max(0.4, minutes / 25))
  const weights = {
    common: guaranteed ? 0 : RARITY.common.weight,
    rare: RARITY.rare.weight * luck,
    legendary: RARITY.legendary.weight * luck,
  }
  const total = weights.common + weights.rare + weights.legendary
  let r = rand() * total
  let rarity = 'legendary'
  for (const key of ['common', 'rare', 'legendary']) {
    if (r < weights[key]) {
      rarity = key
      break
    }
    r -= weights[key]
  }
  const pool = ANIMALS.filter((a) => a.rarity === rarity)
  return pool[Math.floor(rand() * pool.length)]
}
