// Pixel animals. Each sprite is 16x16: one string per row, one character per
// pixel. "." is transparent; every other character looks up a colour in `pal`.
// To add an animal, copy an entry, redraw the rows, and give it a rarity.

const EYE = '#2B1D14'

export const ANIMALS = [
  {
    id: 'chick',
    name: 'Chick',
    rarity: 'common',
    pal: { k: '#6B4A12', y: '#FFD84A', Y: '#F2B32C', o: '#F58A1F', e: EYE, p: '#FF9F9F' },
    px: [
      '................',
      '.......kk.......',
      '......kyyk......',
      '....kkkyykkk....',
      '...kyyyyyyyyk...',
      '..kyyyyyyyyyyk..',
      '..kyyeyyyyeyyk..',
      '..kyyeyyyyeyyk..',
      '..kypyyooyypyk..',
      '.kkyyyyooyyyykk.',
      '.kYyyyyyyyyyyYk.',
      '.kYyyyyyyyyyyYk.',
      '..kyyyyyyyyyyk..',
      '...kyyyyyyyyk...',
      '....kkokkokk....',
      '.....oo..oo.....',
    ],
  },
  {
    id: 'bunny',
    name: 'Bunny',
    rarity: 'common',
    pal: { k: '#7A6A5E', w: '#FBF6EE', p: '#F7A8B8', n: '#E86A8A', e: EYE },
    px: [
      '...kk......kk...',
      '..kwwk....kwwk..',
      '..kwpk....kwpk..',
      '..kwpk....kwpk..',
      '..kwpk....kwpk..',
      '..kwwkkkkkkwwk..',
      '..kwwwwwwwwwwk..',
      '.kwwwwwwwwwwwwk.',
      '.kwwewwwwwwewwk.',
      '.kwwewwwwwwewwk.',
      '.kwpwwwnnwwwpwk.',
      '.kwwwwwwwwwwwwk.',
      '..kwwwwwwwwwwk..',
      '..kwwwwwwwwwwk..',
      '...kwwkkkkwwk...',
      '....kk....kk....',
    ],
  },
  {
    id: 'cat',
    name: 'Cat',
    rarity: 'common',
    pal: { k: '#6B3A12', o: '#F2A04A', d: '#C97428', w: '#FFF3E0', p: '#F7A8B8', n: '#E86A8A', e: EYE },
    px: [
      '................',
      '..kk........kk..',
      '.kook......kook.',
      '.kopokkkkkkopok.',
      '.kooooddddooook.',
      '.kooooooooooook.',
      '.kooeooooooeook.',
      '.kooeooooooeook.',
      '.kpoowwnnwwoopk.',
      '..kowwwwwwwwok..',
      '...kkwwwwwwkk...',
      '...koowwwwook.kk',
      '...koooooooookok',
      '...kookookookkok',
      '...kkkkkkkkkkkk.',
      '................',
    ],
  },
  {
    id: 'frog',
    name: 'Frog',
    rarity: 'common',
    pal: { k: '#24551B', g: '#6CC24A', l: '#C9EE9A', w: '#FFFFFF', p: '#F59A9A', e: EYE },
    px: [
      '................',
      '................',
      '..kkk......kkk..',
      '.kgggk....kgggk.',
      '.kgwekkkkkkwegk.',
      '.kgweggggggwegk.',
      '.kggggggggggggk.',
      '.kgpggggggggpgk.',
      '.kggkggggggkggk.',
      '.kgggkkkkkkgggk.',
      '..kggggggggggk..',
      '..kgllllllllgk..',
      '.kkgllllllllgkk.',
      '.kggkggggggkggk.',
      '..kk.kkkkkk.kk..',
      '................',
    ],
  },
  {
    id: 'pig',
    name: 'Pig',
    rarity: 'common',
    pal: { k: '#8A3D52', p: '#F9B4C0', P: '#EE8AA0', e: EYE },
    px: [
      '................',
      '................',
      '..kkk......kkk..',
      '.kpPpkkkkkkpPpk.',
      '.kppppppppppppk.',
      '.kppppppppppppk.',
      '.kppeppppppeppk.',
      '.kppeppppppeppk.',
      '.kpppPPPPPPpppk.',
      '.kpppPkPPkPpppk.',
      '.kpppPPPPPPpppk.',
      '..kppppppppppk..',
      '..kppppppppppk..',
      '..kppkppppkppk..',
      '...kk.kkkk.kk...',
      '................',
    ],
  },
  {
    id: 'mouse',
    name: 'Mouse',
    rarity: 'common',
    pal: { k: '#4A4C59', g: '#B9BCC6', p: '#F7A8B8', n: '#E86A8A', w: '#F4F4F7', e: EYE },
    px: [
      '................',
      '.kkk........kkk.',
      'kgggk......kgggk',
      'kgpgk......kgpgk',
      'kgpggkkkkkkggpgk',
      '.kggggggggggggk.',
      '.kggggggggggggk.',
      '.kggeggggggeggk.',
      '.kggeggggggeggk.',
      '.kgpgggnngggpgk.',
      '..kggwwwwwwggk..',
      '..kgwwwwwwwwgk..',
      '..kgwwwwwwwwgk..',
      '...kgwwwwwwgk...',
      '...kkkk..kkkk...',
      '................',
    ],
  },
  {
    id: 'fox',
    name: 'Fox',
    rarity: 'rare',
    pal: { k: '#6B2E0E', o: '#EE7A2E', d: '#3A2A22', w: '#FFF6EA', n: '#2B1D14', e: EYE },
    px: [
      '.kk..........kk.',
      '.kdk........kdk.',
      '.kook......kook.',
      '.koookkkkkkoook.',
      '.kooooooooooook.',
      '.kooeooooooeook.',
      '.kooeooooooeook.',
      '.kwwoooooooowwk.',
      '.kwwwwonnowwwwk.',
      '..kwwwwwwwwwwk..',
      '...kkwwwwwwkk...',
      '...koowwwwook.k.',
      '...koowwwwookkok',
      '...koooooooookwk',
      '...kkkkkkkkkkkk.',
      '................',
    ],
  },
  {
    id: 'panda',
    name: 'Panda',
    rarity: 'rare',
    pal: { k: '#2A2A33', w: '#FAFAFA', b: '#2A2A33', e: '#FFFFFF', n: '#2A2A33' },
    px: [
      '................',
      '.kkk........kkk.',
      'kbbbk......kbbbk',
      'kbbbkkkkkkkkbbbk',
      '.kkwwwwwwwwwwkk.',
      '.kwwwwwwwwwwwwk.',
      '.kwbbbwwwwbbbwk.',
      '.kwbebwwwwbebwk.',
      '.kwwbbwnnwbbwwk.',
      '.kwwwwwwwwwwwwk.',
      '..kwwwwwwwwwwk..',
      '..kbbwwwwwwbbk..',
      '..kbbwwwwwwbbk..',
      '..kbbbwwwwbbbk..',
      '...kkkkkkkkkk...',
      '................',
    ],
  },
  {
    id: 'penguin',
    name: 'Penguin',
    rarity: 'rare',
    pal: { k: '#172038', n: '#2D3E63', w: '#FAFBFF', o: '#F59A23', e: EYE },
    px: [
      '................',
      '.....kkkkkk.....',
      '....knnnnnnk....',
      '...knnnnnnnnk...',
      '..knnwwnnwwnnk..',
      '..knwwwwwwwwnk..',
      '..knwewwwwewnk..',
      '..knwwwoowwwnk..',
      '.kknwwwoowwwnkk.',
      '.knnwwwwwwwwnnk.',
      '.knnwwwwwwwwnnk.',
      '.knnwwwwwwwwnnk.',
      '..knwwwwwwwwnk..',
      '..knnwwwwwwnnk..',
      '...kookkkkook...',
      '....kk....kk....',
    ],
  },
  {
    id: 'owl',
    name: 'Owl',
    rarity: 'rare',
    pal: { k: '#4A2F17', b: '#9A6B3F', w: '#FFF8E7', o: '#F2A81D', c: '#EBD2A4', e: EYE },
    px: [
      '................',
      '..k..........k..',
      '.kbk........kbk.',
      '.kbbkkkkkkkkbbk.',
      '.kbbbbbbbbbbbbk.',
      '.kbwwwbbbbwwwbk.',
      '.kbwewbbbbwewbk.',
      '.kbwwwboobwwwbk.',
      '.kbbbbboobbbbbk.',
      '.kbbccccccccbbk.',
      '.kbbcbccccbcbbk.',
      '.kbbccccccccbbk.',
      '..kbbcbccbcbbk..',
      '...kbbbbbbbbk...',
      '....kookkook....',
      '................',
    ],
  },
  {
    id: 'axolotl',
    name: 'Axolotl',
    rarity: 'legendary',
    pal: { k: '#9A3A63', a: '#FFB7CE', l: '#FFE0EA', f: '#E8498A', p: '#FF8FB0', e: EYE },
    px: [
      '................',
      '.k............k.',
      'kfk..kkkkkk..kfk',
      '.kfkkaaaaaakkfk.',
      'kfkaaaaaaaaaakfk',
      '.kkaaaaaaaaaakk.',
      'kfkaeaaaaaaeakfk',
      '.kkaeaaaaaaeakk.',
      '..kapaakkaapak..',
      '..kaaaaaaaaaak..',
      '...kkaaaaaakk...',
      '...kaallllaak...',
      '..kkaallllaakk..',
      '...kaaallaaakkk.',
      '...kkkkkkkkkaak.',
      '............kk..',
    ],
  },
  {
    id: 'capybara',
    name: 'Capybara',
    rarity: 'legendary',
    pal: { k: '#5A3A1E', b: '#B9814D', d: '#8F5E33', n: '#3A2414', o: '#F58A1F', g: '#4E9A3A', e: EYE },
    px: [
      '.......gk.......',
      '......kook......',
      '.....kooook.....',
      '..kk.kooook.kk..',
      '.kbbkkkkkkkkbbk.',
      '.kbbbbbbbbbbbbk.',
      '.kbbbbbbbbbbbbk.',
      '.kbebbbbbbbbebk.',
      '.kbbbbddddbbbbk.',
      '.kbbbdnddndbbbk.',
      '.kbbbddddddbbbk.',
      '.kbbbbbbbbbbbbk.',
      '.kbbbbbbbbbbbbk.',
      '..kbbkbbbbkbbk..',
      '..kkkkkkkkkkkk..',
      '................',
    ],
  },
]

export const ANIMAL_BY_ID = Object.fromEntries(ANIMALS.map((a) => [a.id, a]))

export const RARITY = {
  common: { label: 'Common', weight: 72 },
  rare: { label: 'Rare', weight: 23 },
  legendary: { label: 'Legendary', weight: 5 },
}

// The egg. "s" pixels take the current mode colour, so the egg matches the theme.
export const EGG = {
  pal: { k: '#6B5A45', w: '#FFF8EC', d: '#E9D9BE', s: 'var(--accent)' },
  px: [
    '................',
    '......kkkk......',
    '.....kwwwwk.....',
    '....kwwwwwwk....',
    '....kwwsswwk....',
    '...kwwwsswwwk...',
    '...kwwwwwwwwk...',
    '..kwwwwwwwwwwk..',
    '..kwsswwwwwwwk..',
    '..kwsswwwwsswk..',
    '..kwwwwwwwsswk..',
    '..kwwwwwwwwwwk..',
    '...kwwwwwwwwk...',
    '...kddwwwwddk...',
    '....kkddddkk....',
    '......kkkk......',
  ],
}

// Cracks appear as the focus session progresses: [x, y] pixels painted dark.
export const CRACKS = [
  [],
  [[6, 8], [7, 7], [8, 6], [9, 7]],
  [[4, 6], [5, 7], [6, 8], [7, 7], [8, 6], [9, 7], [10, 8], [11, 7]],
  [[3, 7], [4, 6], [5, 7], [6, 8], [7, 7], [8, 6], [9, 7], [10, 8], [11, 7], [12, 6], [6, 9], [7, 10], [8, 5]],
]

// Pick the animal for a finished focus session.
//   minutes    - length of the session; longer sessions improve the odds of rarer animals
//   guaranteed - true on the last session before a long break: at least a rare
export function rollAnimal(minutes, guaranteed = false, rand = Math.random) {
  const luck = Math.min(2.4, Math.max(0.4, minutes / 25))
  const weights = {
    common: guaranteed ? 0 : RARITY.common.weight,
    rare: RARITY.rare.weight * luck,
    legendary: RARITY.legendary.weight * luck,
  }
  const total = weights.common + weights.rare + weights.legendary
  let r = rand() * total
  let rarity = 'legendary'
  for (const key of ['common', 'rare', 'legendary']) {
    if (r < weights[key]) {
      rarity = key
      break
    }
    r -= weights[key]
  }
  const pool = ANIMALS.filter((a) => a.rarity === rarity)
  return pool[Math.floor(rand() * pool.length)]
}
